from flask import Flask, request, jsonify, render_template
from datetime import datetime
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

app = Flask(__name__)
reports = []

# Configure your email here
SENDER_EMAIL = "your.gmail@gmail.com"
SENDER_PASSWORD = "your_app_password"
MUNICIPALITY_EMAIL = "your.gmail@gmail.com"

def send_municipality_email(report):
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"🗑️ Trash Detected — Report #{report['id']} | {report['time']}"
        msg['From'] = SENDER_EMAIL
        msg['To'] = MUNICIPALITY_EMAIL

        maps_link = f"https://www.google.com/maps?q={report['lat']},{report['lon']}"

        html = f"""
        <html><body style="font-family: Arial; padding: 20px;">
            <h2 style="color: #e74c3c;">🗑️ New Trash Report #{report['id']}</h2>
            <table style="border-collapse: collapse; width: 100%;">
                <tr style="background:#f8f9fa">
                    <td style="padding:10px;border:1px solid #ddd"><b>Time</b></td>
                    <td style="padding:10px;border:1px solid #ddd">{report['time']}</td>
                </tr>
                <tr>
                    <td style="padding:10px;border:1px solid #ddd"><b>Location</b></td>
                    <td style="padding:10px;border:1px solid #ddd">
                        {report['lat']:.5f}, {report['lon']:.5f}<br>
                        <a href="{maps_link}">📍 View on Google Maps</a>
                    </td>
                </tr>
                <tr style="background:#f8f9fa">
                    <td style="padding:10px;border:1px solid #ddd"><b>Confidence</b></td>
                    <td style="padding:10px;border:1px solid #ddd">{report['confidence']*100:.0f}%</td>
                </tr>
            </table>
            <br>
            <p style="color:#666">This report was automatically generated by TrashGlasses — 
            an AI-powered wearable trash detection system.</p>
        </body></html>
        """

        msg.attach(MIMEText(html, 'html'))
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, MUNICIPALITY_EMAIL, msg.as_string())
        server.quit()
        print(f"✓ Email sent to municipality for report #{report['id']}")

    except Exception as e:
        print(f"✗ Email failed: {e}")

@app.route('/')
def home():
    return render_template('map.html', reports=reports)

@app.route('/report', methods=['POST'])
def receive_report():
    data = request.json
    report = {
        'id': len(reports) + 1,
        'lat': data['lat'],
        'lon': data['lon'],
        'confidence': data['confidence'],
        'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'photo': data.get('photo', '')
    }
    reports.append(report)
    print(f"New report #{report['id']} at {report['lat']}, {report['lon']}")
    send_municipality_email(report)
    return jsonify({'status': 'received', 'id': report['id']})

@app.route('/reports')
def get_reports():
    return jsonify(reports)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)